---
- name: launch Master Node on AWS cloud
  ec2:
         key_name: "{{ keypair }}"
         instance_type: "{{ instance_flavour }}"
         image: "{{ ami_id }}"
         wait: yes
         count: 2
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         group_id: "{{ sg_name }}"
         assign_public_ip: yes
         region: "{{ region_name }}"
         state: present
         aws_access_key: "{{ aws_access_key_id }}"
         aws_secret_key: "{{ aws_secret_access_key }}"
         instance_tags:
           Name: "{{ item }}"
           Cluster: "{{ cluster_tag }}"
           Type: "master"

- name: launch Master and Worker Node on AWS cloud
  ec2:
          key_name: "{{ keypair }}"
          instance_type: "{{ instance_flavour }}"
          image: "{{ ami_id }}"
          wait: yes
          count: 2
          vpc_subnet_id: "{{ vpc_subnet_id }}"
          group_id: "{{ sg_name }}"
          assign_public_ip: yes
          region: "{{ region_name }}"
          state: present
          aws_access_key: "{{ aws_access_key_id }}"
          aws_secret_key: "{{ aws_secret_access_key }}"
          instance_tags:
            Name: "{{ item }}"
            Cluster: "{{ cluster_tag }}"
            Type: "worker"
  register: ec2
  loop: "{{ hosts_tag }}"


 - name: Add 1st instance to host group ec2_master
   add_host:
     hostname: "{{ ec2.results[0].instances[0].public_ip }}"
     groupname: ec2_master

 - name: Add 2nd instance to host group ec2_worker
   add_host:
     hostname: "{{ ec2.results[1].instances[0].public_ip }}"
     groupname: ec2_worker

 - name: Add 3rd instance to host group ec2_worker
   add_host:
    hostname: "{{ ec2.results[2].instances[0].public_ip }}"
    groupname: ec2_worker
